// Curated name data for data/sky/stars.json (merged by build-stars.mjs).
//
// ARABIC: IAU (WGSN) star names whose origin is Arabic, with the original Arabic, a transliteration and the meaning.
// Etymologies follow P. Kunitzsch & T. Smart, "A Dictionary of Modern Star Names" (2nd ed., Sky Publishing, 2006),
// which is arranged alphabetically, so each entry is cited "s.v. <name>". Only names whose Arabic origin and meaning are
// well established there are listed. Where the derivation is disputed or uncertain (e.g. Alioth, Mirach, Mirzam, Scheat,
// Algenib, Hassaleh, Athebyne, Lesath, Kraz, Tejat, Matar), the star is deliberately left WITHOUT Arabic fields.
// Every entry still needs the project's scholar sign-off before public launch (see data/sky/README.md).
//
// `part`: "full" = the whole IAU name comes from the Arabic; "hybrid" = Arabic word + Latin/Greek (e.g. Kaus Australis).

/** @type {Record<string, { ar: string; tr: string; en: string; arMeaning: string; part?: "full" | "hybrid" }>} */
export const ARABIC = {
  // Lyra, Aquila, Cygnus
  Vega: { ar: "النسر الواقع", tr: "al-nasr al-wāqiʿ", en: "the swooping eagle", arMeaning: "النسر الهاوي المنقضّ" },
  Altair: { ar: "النسر الطائر", tr: "al-nasr al-ṭāʾir", en: "the flying eagle", arMeaning: "النسر المحلّق" },
  Deneb: { ar: "ذنب الدجاجة", tr: "dhanab al-dajāja", en: "the tail of the hen", arMeaning: "ذيل الدجاجة (كوكبة الدجاجة)" },
  Sadr: { ar: "الصدر", tr: "al-ṣadr", en: "the chest (of the hen)", arMeaning: "صدر الدجاجة" },
  Aljanah: { ar: "الجناح", tr: "al-janāḥ", en: "the wing (of the hen)", arMeaning: "جناح الدجاجة" },
  Fawaris: { ar: "الفوارس", tr: "al-fawāris", en: "the horsemen", arMeaning: "الفرسان" },
  Okab: { ar: "العقاب", tr: "al-ʿuqāb", en: "the eagle", arMeaning: "طائر العقاب" },

  // Taurus, Orion and the river
  Aldebaran: { ar: "الدبران", tr: "al-dabarān", en: "the follower (of the Pleiades)", arMeaning: "التابع، لأنه يتبع الثريا" },
  Elnath: { ar: "النطح", tr: "al-naṭḥ", en: "the butting (with the horns)", arMeaning: "النطح بالقرن" },
  Betelgeuse: { ar: "يد الجوزاء", tr: "yad al-jawzāʾ", en: "the hand of al-Jawzāʾ", arMeaning: "يد الجوزاء (صورة الجبار عند العرب)" },
  Rigel: { ar: "رجل الجوزاء", tr: "rijl al-jawzāʾ", en: "the foot of al-Jawzāʾ", arMeaning: "قدم الجوزاء (صورة الجبار عند العرب)" },
  Alnilam: { ar: "النظام", tr: "al-niẓām", en: "the string (of pearls)", arMeaning: "خيط اللؤلؤ المنظوم" },
  Alnitak: { ar: "النطاق", tr: "al-niṭāq", en: "the girdle", arMeaning: "الحزام" },
  Mintaka: { ar: "المنطقة", tr: "al-minṭaqa", en: "the belt", arMeaning: "الحزام" },
  Saiph: { ar: "سيف", tr: "sayf", en: "sword (of the giant)", arMeaning: "سيف الجبار" },
  Achernar: { ar: "آخر النهر", tr: "ākhir al-nahr", en: "the end of the river", arMeaning: "نهاية النهر (كوكبة النهر)" },
  Acamar: { ar: "آخر النهر", tr: "ākhir al-nahr", en: "the end of the river", arMeaning: "نهاية النهر (كوكبة النهر)" },
  Cursa: { ar: "الكرسي", tr: "al-kursī", en: "the footstool (of al-Jawzāʾ)", arMeaning: "كرسي الجوزاء" },
  Zaurak: { ar: "الزورق", tr: "al-zawraq", en: "the boat", arMeaning: "القارب" },
  Arneb: { ar: "الأرنب", tr: "al-arnab", en: "the hare", arMeaning: "الأرنب" },
  Nihal: { ar: "النهال", tr: "al-nihāl", en: "the camels slaking their thirst", arMeaning: "الإبل التي تروي عطشها" },

  // Canis Major / Minor, Gemini, Columba
  Adhara: { ar: "العذارى", tr: "al-ʿadhārā", en: "the maidens", arMeaning: "الفتيات العذارى" },
  Wezen: { ar: "الوزن", tr: "al-wazn", en: "the weight", arMeaning: "الثِّقل" },
  Aludra: { ar: "العذراء", tr: "al-ʿadhrāʾ", en: "the maiden", arMeaning: "الفتاة العذراء" },
  Gomeisa: { ar: "الغميصاء", tr: "al-ghumayṣāʾ", en: "the bleary-eyed one", arMeaning: "ذات العين الدامعة" },
  Alhena: { ar: "الهنعة", tr: "al-hanʿa", en: "the brand (on a camel's neck)", arMeaning: "الوسم على عنق البعير" },
  Phact: { ar: "الفاختة", tr: "al-fākhita", en: "the ring-dove", arMeaning: "طائر الفاختة (اليمامة المطوّقة)" },

  // Leo, Hydra, Corvus
  Algieba: { ar: "الجبهة", tr: "al-jabha", en: "the forehead (of the lion)", arMeaning: "جبهة الأسد" },
  Denebola: { ar: "ذنب الأسد", tr: "dhanab al-asad", en: "the tail of the lion", arMeaning: "ذيل الأسد" },
  "Ras Elased Australis": { ar: "رأس الأسد", tr: "raʾs al-asad", en: "the head of the lion (southern star)", arMeaning: "رأس الأسد (النجم الجنوبي منهما)", part: "hybrid" },
  Alphard: { ar: "الفرد", tr: "al-fard", en: "the solitary one", arMeaning: "المنفرد (فرد الشجاع)" },
  Algorab: { ar: "الغراب", tr: "al-ghurāb", en: "the crow", arMeaning: "طائر الغراب" },
  Gienah: { ar: "الجناح", tr: "al-janāḥ", en: "the wing (of the crow)", arMeaning: "جناح الغراب" },

  // Great Bear, Little Bear, Draco
  Dubhe: { ar: "الدب", tr: "al-dubb", en: "the bear", arMeaning: "الدب (ظهر الدب الأكبر)" },
  Merak: { ar: "المراق", tr: "al-marāqq", en: "the loins (of the bear)", arMeaning: "مراقّ البطن من الدب" },
  Phecda: { ar: "الفخذ", tr: "al-fakhidh", en: "the thigh (of the bear)", arMeaning: "فخذ الدب" },
  Mizar: { ar: "المئزر", tr: "al-miʾzar", en: "the waist-cloth", arMeaning: "الإزار" },
  Alkaid: { ar: "القائد", tr: "al-qāʾid", en: "the leader (of the daughters of the bier)", arMeaning: "قائد بنات نعش" },
  Kochab: { ar: "الكوكب", tr: "al-kawkab", en: "the star", arMeaning: "النجم (الكوكب الشمالي)" },
  Pherkad: { ar: "الفرقد", tr: "al-farqad", en: "the calf", arMeaning: "ولد البقرة الوحشية (أحد الفرقدين)" },
  Eltanin: { ar: "التنين", tr: "al-tinnīn", en: "the dragon", arMeaning: "التنين (رأس التنين)" },
  Rastaban: { ar: "رأس الثعبان", tr: "raʾs al-thuʿbān", en: "the head of the serpent", arMeaning: "رأس الحية" },
  Thuban: { ar: "الثعبان", tr: "al-thuʿbān", en: "the serpent", arMeaning: "الحية" },

  // Perseus, Auriga, Andromeda, Cassiopeia, Cepheus
  Mirfak: { ar: "المرفق", tr: "al-mirfaq", en: "the elbow", arMeaning: "المرفق" },
  Algol: { ar: "رأس الغول", tr: "raʾs al-ghūl", en: "the head of the ghoul", arMeaning: "رأس الغول" },
  Menkalinan: { ar: "منكب ذي العنان", tr: "mankib dhī al-ʿinān", en: "the shoulder of the rein-holder", arMeaning: "كتف ممسك الأعنّة" },
  Mahasim: { ar: "المعصم", tr: "al-miʿṣam", en: "the wrist (of the rein-holder)", arMeaning: "معصم ممسك الأعنّة" },
  Alpheratz: { ar: "سرة الفرس", tr: "surrat al-faras", en: "the navel of the horse", arMeaning: "سرّة الفرس" },
  Almach: { ar: "عناق الأرض", tr: "ʿanāq al-arḍ", en: "the caracal", arMeaning: "الوشق الصحراوي (عناق الأرض)" },
  Schedar: { ar: "الصدر", tr: "al-ṣadr", en: "the breast (of the lady in the chair)", arMeaning: "صدر ذات الكرسي" },
  Caph: { ar: "الكف", tr: "al-kaff", en: "the palm (of the dyed hand)", arMeaning: "الكف الخضيب" },
  Ruchbah: { ar: "ركبة", tr: "rukba", en: "the knee (of the lady in the chair)", arMeaning: "ركبة ذات الكرسي" },
  Alderamin: { ar: "الذراع اليمين", tr: "al-dhirāʿ al-yamīn", en: "the right forearm", arMeaning: "الذراع اليمنى" },

  // Pegasus, Aquarius, Capricornus, Pisces Austrinus, Grus, Phoenix, Cetus
  Markab: { ar: "مركب", tr: "markab", en: "something to ride on (the saddle)", arMeaning: "ما يُركب (السرج)" },
  Enif: { ar: "أنف", tr: "anf", en: "the nose (of the horse)", arMeaning: "أنف الفرس" },
  Sadalmelik: { ar: "سعد الملك", tr: "saʿd al-malik", en: "the luck of the king", arMeaning: "سعد الملك" },
  Sadalsuud: { ar: "سعد السعود", tr: "saʿd al-suʿūd", en: "the luckiest of the lucky", arMeaning: "أسعد السعود" },
  "Deneb Algedi": { ar: "ذنب الجدي", tr: "dhanab al-jady", en: "the tail of the goat", arMeaning: "ذيل الجدي" },
  Fomalhaut: { ar: "فم الحوت", tr: "fam al-ḥūt", en: "the mouth of the fish", arMeaning: "فم الحوت (الجنوبي)" },
  Alnair: { ar: "النير", tr: "al-nayyir", en: "the bright one", arMeaning: "المضيء (النيّر)" },
  Aldhanab: { ar: "الذنب", tr: "al-dhanab", en: "the tail", arMeaning: "الذيل" },
  Ankaa: { ar: "العنقاء", tr: "al-ʿanqāʾ", en: "the phoenix (a legendary bird)", arMeaning: "طائر العنقاء الأسطوري" },
  Diphda: { ar: "الضفدع الثاني", tr: "al-ḍifdiʿ al-thānī", en: "the second frog", arMeaning: "الضفدع الثاني" },
  Menkar: { ar: "المنخر", tr: "al-minkhar", en: "the nostril (of the sea monster)", arMeaning: "منخر قيطس" },
  Hamal: { ar: "الحمل", tr: "al-ḥamal", en: "the lamb", arMeaning: "الحمل (صغير الضأن)" },
  Sheratan: { ar: "الشرطان", tr: "al-sharaṭān", en: "the two signs", arMeaning: "العلامتان" },

  // Scorpius, Libra, Ophiuchus, Serpens, Hercules, Boötes, Corona Borealis, Sagittarius
  Acrab: { ar: "العقرب", tr: "al-ʿaqrab", en: "the scorpion", arMeaning: "العقرب" },
  Dschubba: { ar: "الجبهة", tr: "al-jabha", en: "the forehead (of the scorpion)", arMeaning: "جبهة العقرب" },
  Shaula: { ar: "الشولة", tr: "al-shawla", en: "the raised tail (the sting)", arMeaning: "ذيل العقرب المرفوع" },
  Alniyat: { ar: "النياط", tr: "al-niyāṭ", en: "the arteries (of the heart)", arMeaning: "نياط القلب" },
  Zubenelgenubi: { ar: "الزبانى الجنوبي", tr: "al-zubānā al-janūbī", en: "the southern claw", arMeaning: "الزبانى الجنوبي (مخلب العقرب)" },
  Zubeneschamali: { ar: "الزبانى الشمالي", tr: "al-zubānā al-shamālī", en: "the northern claw", arMeaning: "الزبانى الشمالي (مخلب العقرب)" },
  Rasalhague: { ar: "رأس الحواء", tr: "raʾs al-ḥawwāʾ", en: "the head of the snake-charmer", arMeaning: "رأس الحوّاء" },
  Cebalrai: { ar: "كلب الراعي", tr: "kalb al-rāʿī", en: "the shepherd's dog", arMeaning: "كلب الراعي" },
  Sabik: { ar: "السابق", tr: "al-sābiq", en: "the one who goes before", arMeaning: "السابق" },
  "Yed Prior": { ar: "يد", tr: "yad", en: "hand (the leading star of the pair)", arMeaning: "اليد (النجم المتقدّم من الاثنين)", part: "hybrid" },
  Unukalhai: { ar: "عنق الحية", tr: "ʿunuq al-ḥayya", en: "the neck of the snake", arMeaning: "عنق الحية" },
  Rasalgethi: { ar: "رأس الجاثي", tr: "raʾs al-jāthī", en: "the head of the kneeling one", arMeaning: "رأس الجاثي على ركبتيه" },
  Izar: { ar: "إزار", tr: "izār", en: "the waist-cloth", arMeaning: "الإزار" },
  Muphrid: { ar: "المفرد", tr: "al-mufrid", en: "the solitary one", arMeaning: "المنفرد" },
  Alphecca: { ar: "الفكة", tr: "al-fakka", en: "the broken (ring)", arMeaning: "الفكة (الحلقة المكسورة)" },
  "Kaus Australis": { ar: "القوس", tr: "al-qaws", en: "the bow (southern part)", arMeaning: "القوس (الجزء الجنوبي)", part: "hybrid" },
  "Kaus Media": { ar: "القوس", tr: "al-qaws", en: "the bow (middle part)", arMeaning: "القوس (الجزء الأوسط)", part: "hybrid" },
  "Kaus Borealis": { ar: "القوس", tr: "al-qaws", en: "the bow (northern part)", arMeaning: "القوس (الجزء الشمالي)", part: "hybrid" },
  Alnasl: { ar: "النصل", tr: "al-naṣl", en: "the arrowhead", arMeaning: "نصل السهم" },
  Albaldah: { ar: "البلدة", tr: "al-balda", en: "the town (a lunar mansion)", arMeaning: "البلدة (منزلة من منازل القمر)" },

  // Southern sky
  "Rigil Kentaurus": { ar: "رجل قنطورس", tr: "rijl qanṭūris", en: "the foot of the centaur", arMeaning: "قدم قنطورس" },
  Menkent: { ar: "منكب قنطورس", tr: "mankib qanṭūris", en: "the shoulder of the centaur", arMeaning: "كتف قنطورس", part: "hybrid" },
  Suhail: { ar: "سهيل", tr: "suhayl", en: "Suhayl, a traditional Arabic name for bright southern stars, above all Canopus", arMeaning: "سهيل: اسم عربي قديم لنجوم جنوبية لامعة، أشهرها نجم سهيل (كانوبس)" },
  Alsephina: { ar: "السفينة", tr: "al-safīna", en: "the ship", arMeaning: "السفينة" },
  Markeb: { ar: "مركب", tr: "markab", en: "something to ride on (a vessel)", arMeaning: "ما يُركب (المركب)" },
};

/** Arabic-script rendering of IAU names that are NOT of Arabic origin (a transliteration, not a translation). */
export const NAME_AR = {
  Sirius: "سيريوس",
  Canopus: "كانوبوس",
  Arcturus: "أركتوروس",
  Capella: "كابيلا",
  Procyon: "بروكيون",
  Hadar: "هادار",
  Acrux: "أكروكس",
  Spica: "سبايكا",
  Antares: "أنتاريس",
  Pollux: "بولوكس",
  Mimosa: "ميموزا",
  Regulus: "ريغولوس",
  Castor: "كاستور",
  Gacrux: "غاكروكس",
  Bellatrix: "بيلاتريكس",
  Miaplacidus: "ميابلاسيدوس",
  Alioth: "أليوث",
  Avior: "أفيور",
  Sargas: "سارغاس",
  Atria: "أتريا",
  Peacock: "بيكوك",
  Polaris: "بولاريس",
  Mirzam: "ميرزام",
  Nunki: "نونكي",
  Mirach: "ميراخ",
  Tiaki: "تياكي",
  Cih: "تسيه",
  Naos: "ناووس",
  Aspidiske: "أسبيديسكي",
  Larawag: "لاراواغ",
  Scheat: "شيات",
  Zosma: "زوسما",
  Ascella: "أسيلا",
  Kraz: "كراز",
  Hassaleh: "هاساليه",
  Lesath: "ليساث",
  Tarazed: "تارازد",
  Athebyne: "أثيباين",
  Porrima: "بوريما",
  Hatysa: "هاتيسا",
  Kornephoros: "كورنيفوروس",
  Imai: "إيماي",
  Paikauhale: "بايكاوهالي",
  Algenib: "ألجنيب",
  Tureis: "توريس",
  Alcyone: "ألكيوني",
  Vindemiatrix: "فينديمياتريكس",
  Tejat: "تيجات",
  "Cor Caroli": "كور كارولي",
  Fang: "فانغ",
  Matar: "ماتار",
  Tianguan: "تيانغوان",
  Xamidimura: "خاميديمورا",
};

/** IAU constellation abbreviation → [Latin name, Arabic name]. */
export const CONSTELLATIONS = {
  And: ["Andromeda", "المرأة المسلسلة"],
  Aql: ["Aquila", "العقاب"],
  Aqr: ["Aquarius", "الدلو"],
  Ara: ["Ara", "المجمرة"],
  Ari: ["Aries", "الحمل"],
  Aur: ["Auriga", "ممسك الأعنة"],
  Boo: ["Boötes", "العوّاء"],
  CMa: ["Canis Major", "الكلب الأكبر"],
  CMi: ["Canis Minor", "الكلب الأصغر"],
  CVn: ["Canes Venatici", "كلاب الصيد"],
  Cap: ["Capricornus", "الجدي"],
  Car: ["Carina", "القاعدة"],
  Cas: ["Cassiopeia", "ذات الكرسي"],
  Cen: ["Centaurus", "قنطورس"],
  Cep: ["Cepheus", "قيفاوس"],
  Cet: ["Cetus", "قيطس"],
  Col: ["Columba", "الحمامة"],
  CrB: ["Corona Borealis", "الإكليل الشمالي"],
  Crv: ["Corvus", "الغراب"],
  Cru: ["Crux", "الصليب الجنوبي"],
  Cyg: ["Cygnus", "الدجاجة"],
  Dra: ["Draco", "التنين"],
  Eri: ["Eridanus", "النهر"],
  Gem: ["Gemini", "التوأمان"],
  Gru: ["Grus", "الكركي"],
  Her: ["Hercules", "الجاثي"],
  Hya: ["Hydra", "الشجاع"],
  Hyi: ["Hydrus", "الحية المائية"],
  Leo: ["Leo", "الأسد"],
  Lep: ["Lepus", "الأرنب"],
  Lib: ["Libra", "الميزان"],
  Lup: ["Lupus", "الذئب"],
  Lyr: ["Lyra", "القيثارة"],
  Mus: ["Musca", "الذبابة"],
  Oph: ["Ophiuchus", "الحوّاء"],
  Ori: ["Orion", "الجبار"],
  Pav: ["Pavo", "الطاووس"],
  Peg: ["Pegasus", "الفرس الأعظم"],
  Per: ["Perseus", "حامل رأس الغول"],
  Phe: ["Phoenix", "العنقاء"],
  PsA: ["Piscis Austrinus", "الحوت الجنوبي"],
  Pup: ["Puppis", "الكوثل"],
  Sco: ["Scorpius", "العقرب"],
  Ser: ["Serpens", "الحية"],
  Sgr: ["Sagittarius", "القوس"],
  Tau: ["Taurus", "الثور"],
  TrA: ["Triangulum Australe", "المثلث الجنوبي"],
  Tri: ["Triangulum", "المثلث"],
  Tuc: ["Tucana", "الطوقان"],
  UMa: ["Ursa Major", "الدب الأكبر"],
  UMi: ["Ursa Minor", "الدب الأصغر"],
  Vel: ["Vela", "الشراع"],
  Vir: ["Virgo", "العذراء"],
};
