import data from "../../../data/sky/stars.json";
import { BODIES, type BodyId, type StarRecord } from "./engine";

/** The bundled bright-star catalogue (generated by scripts/sky/build-stars.mjs; works offline). */
export const STARS = data.stars as unknown as StarRecord[];
export const STAR_COUNT = STARS.length;

const byId = new Map(STARS.map((s) => [s.id, s]));
export const getStar = (id: string): StarRecord | null => byId.get(id) ?? null;

export const isBodyId = (id: string): id is BodyId => BODIES.some((b) => b.id === id);
export const getBody = (id: string) => BODIES.find((b) => b.id === id) ?? null;

/** True for any id Sky mode can show a page for (a catalogue star, the Sun, the Moon or a naked-eye planet). */
export const isSkyId = (id: string) => byId.has(id) || isBodyId(id);

export const skyHref = (id: string) => `/sky/star/${encodeURIComponent(id)}`;
